version: '3'

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8600:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
      - daphne

  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
    command: ["gunicorn", "-b", "0.0.0.0:8000", "hexachromixio.wsgi:application"]

  daphne:
    build: .
    expose:
      - "8001"
    volumes:
      - .:/app
    command: ["daphne", "-b", "0.0.0.0", "-p", "8001", "hexachromixio.asgi:application"]
