version: '3.8'

services:
  web:
    image: taylorvance/hexachromix:web-latest
    ports:
      - "8600:80"
    volumes:
      - static:/app/staticfiles
      - ./:/app
    depends_on:
      - gunicorn
      - daphne

  gunicorn:
    image: taylorvance/hexachromixio:latest
    command: "gunicorn -b 0.0.0.0:8000 hexachromixio.wsgi:application"
    environment:
      - "DJANGO_SECRET_KEY=rope-those-lushly"
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=localhost"
      - "DJANGO_DB_ENGINE=django.db.backends.sqlite3"
      - "DJANGO_DB_NAME=/data/db.sqlite3"
      - "DJANGO_LOG_LEVEL=DEBUG"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8600"
    volumes:
      - hexachromix_data:/data
      - static:/app/staticfiles
      - ./:/app

  daphne:
    image: taylorvance/hexachromixio:latest
    command: "daphne -b 0.0.0.0 -p 8001 hexachromixio.asgi:application"
    environment:
      - "DJANGO_SECRET_KEY=rope-those-lushly"
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=localhost"
      - "DJANGO_DB_ENGINE=django.db.backends.sqlite3"
      - "DJANGO_DB_NAME=/data/db.sqlite3"
      - "DJANGO_LOG_LEVEL=DEBUG"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8600"
    volumes:
      - hexachromix_data:/data
      - ./:/app

volumes:
  hexachromix_data:
  static:
