version: '3.8'

services:
  api:
    image: taylorvance/hexachromix:api-latest
    container_name: dev-api

  django:
    image: taylorvance/hexachromixio:latest
    container_name: dev-django
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8600:8000"
    environment:
      - "DJANGO_SECRET_KEY=rope-those-lushly"
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=localhost"
      - "DJANGO_DB_ENGINE=django.db.backends.sqlite3"
      - "DJANGO_DB_NAME=/data/db.sqlite3"
      - "DJANGO_LOG_LEVEL=DEBUG"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8600"
    volumes:
      - hexachromix_data:/data
      - ./:/app

  redis:
    image: redis
    container_name: dev-redis

  celery:
    image: taylorvance/hexachromixio:latest
    container_name: dev-celery
    command: "celery -A hexachromixio worker -l info"
    environment:
      - "DJANGO_SECRET_KEY=rope-those-lushly"
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=localhost"
      - "DJANGO_DB_ENGINE=django.db.backends.sqlite3"
      - "DJANGO_DB_NAME=/data/db.sqlite3"
      - "DJANGO_LOG_LEVEL=INFO"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8600"
    volumes:
      - hexachromix_data:/data
      - ./:/app

volumes:
  hexachromix_data:
