version: '3.8'

services:
  api:
    image: taylorvance/hexachromix:api-latest
    container_name: dev-api

  django:
    image: taylorvance/hexachromixio:latest
    container_name: dev-django
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8600:8000"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DB_ENGINE
      - DJANGO_DB_NAME
      - DJANGO_LOG_LEVEL
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - HEXACHROMIX_API_URL
    volumes:
      - hexachromix_data:/data
      - ./:/app

  celery:
    image: taylorvance/hexachromixio:latest
    container_name: dev-celery
    command: "celery -A hexachromixio worker -l info"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DB_ENGINE
      - DJANGO_DB_NAME
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - HEXACHROMIX_API_URL
    volumes:
      - hexachromix_data:/data
      - ./:/app

  redis:
    image: redis
    container_name: dev-redis

volumes:
  hexachromix_data:
