version: '3.8'

services:
  api:
    image: taylorvance/hexachromix:api-latest

  web:
    image: taylorvance/hexachromix:web-latest
    ports:
      - "8600:80"
    volumes:
      - static:/app/staticfiles
      - ./:/app
    depends_on:
      - gunicorn
      - daphne

  gunicorn:
    image: taylorvance/hexachromixio:latest
    command: "gunicorn -b 0.0.0.0:8000 hexachromixio.wsgi:application"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DB_ENGINE
      - DJANGO_DB_NAME
      - DJANGO_LOG_LEVEL
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - HEXACHROMIX_API_URL
    volumes:
      - hexachromix_data:/data
      - static:/app/staticfiles
      - ./:/app

  daphne:
    image: taylorvance/hexachromixio:latest
    command: "daphne -b 0.0.0.0 -p 8001 hexachromixio.asgi:application"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DB_ENGINE
      - DJANGO_DB_NAME
      - DJANGO_LOG_LEVEL
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - HEXACHROMIX_API_URL
    volumes:
      - hexachromix_data:/data
      - ./:/app

  celery:
    image: taylorvance/hexachromixio:latest
    command: "celery -A hexachromixio worker -l info"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DB_ENGINE
      - DJANGO_DB_NAME
      - DJANGO_LOG_LEVEL
      - DJANGO_CSRF_TRUSTED_ORIGINS
      - HEXACHROMIX_API_URL
    volumes:
      - hexachromix_data:/data
      - ./:/app

  redis:
    image: redis

volumes:
  hexachromix_data:
  static:
