# Generated by Django 3.1 on 2020-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.IntegerField(choices=[(None, 'Pending'), (0, 'Declined'), (1, 'Accepted')], null=True),
        ),
    ]
