# Generated by Django 3.1 on 2020-09-09 19:20

from django.db import migrations, models
import django.db.models.deletion
import hexachromix.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(default=hexachromix.models.Game.gen_uid, editable=False, max_length=12, unique=True)),
                ('variant', models.CharField(choices=[('MRY', 'MRY GCB'), ('MR', 'MR YG CB')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green'), ('C', 'Cyan'), ('B', 'Blue'), ('M', 'Magenta')], max_length=1)),
                ('q', models.SmallIntegerField()),
                ('r', models.SmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexachromix.game')),
            ],
            options={
                'order_with_respect_to': 'game',
            },
        ),
    ]
