# Generated by Django 3.1 on 2020-09-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hexachromix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='move',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('MRY', 'MRY GCB'), ('RGB', 'RGB CMY'), ('MR', 'MR YG CB'), ('RC', 'RC YB GM'), ('R', 'R Y G C B M')], max_length=3),
        ),
    ]
