# Generated by Django 3.1 on 2020-09-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexachromix', '0002_auto_20200923_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('MRY', 'MRY GCB'), ('RGB', 'RGB CMY'), ('MR', 'MR YG CB'), ('RC', 'RC BY GM'), ('R', 'R Y G C B M')], max_length=3),
        ),
    ]
