# Generated by Django 5.0.1 on 2024-01-05 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexachromix', '0004_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(max_length=26, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('MRY', 'MRY GCB'), ('MR', 'MR YG CB'), ('R', 'R Y G C B M')], max_length=3),
        ),
    ]
