# Generated by Django 5.0.1 on 2024-01-05 20:29

from django.db import migrations

from hexachromix.models import Game


def gen_code(apps, schema_editor):
    OldGame = apps.get_model("hexachromix", "Game")
    for row in OldGame.objects.all():
        row.code = Game.gen_code()
        row.save(update_fields=["code"])

class Migration(migrations.Migration):

    dependencies = [
        ('hexachromix', '0005_game_code_alter_game_variant'),
    ]

    operations = [
        migrations.RunPython(gen_code),
    ]
