# Generated by Django 5.0.1 on 2024-01-05 20:29

from django.db import migrations, models

from hexachromix.models import Game


class Migration(migrations.Migration):

    dependencies = [
        ('hexachromix', '0006_auto_20240105_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(default=Game.gen_code, editable=False, max_length=26, unique=True),
            preserve_default=False,
        ),
    ]
