# Generated by Django 5.0.1 on 2024-01-11 12:07

import hexachromix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexachromix', '0007_auto_20240105_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(default=hexachromix.models.Game.gen_code, editable=False, max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.CharField(choices=[('MRY', 'MRY GCB'), ('MR', 'MR YG CB'), ('R', 'R Y G C B M')], editable=False, max_length=3),
        ),
    ]
