# Generated by Django 5.0.1 on 2024-01-15 20:34

from django.db import migrations

from hexachromix.utils import HexachromixState

def calc_hfen(apps, schema_editor):
    # 2024-01-16 This didn't work. Disabling. See 0014_auto_20240116_1405.py for take 2.
    return

    Move = apps.get_model('hexachromix', 'Move')
    Game = apps.get_model('hexachromix', 'Game')
    for game in Game.objects.all():
        state = HexachromixState(variant=game.variant)
        for move in Move.objects.filter(game=game):
            state = state.make_move((move.q, move.r))
            if not move.tmp_hfen:
                move.tmp_hfen = state.hfen
                move.save(update_fields=['tmp_hfen'])

class Migration(migrations.Migration):
    dependencies = [
        ('hexachromix', '0010_move_tmp_hfen'),
    ]

    operations = [
        migrations.RunPython(calc_hfen),
    ]
