# Generated by Django 5.0.1 on 2024-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexachromix', '0012_remove_move_tmp_hfen_move_hfen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='hfen',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
