# Generated by Django 5.0.1 on 2024-01-16 14:05

from django.db import migrations

from hexachromix.utils import HexachromixState
from hexachromix.models import Game, Move

import logging
logger = logging.getLogger(__name__)

def calc_hfen(apps, schema_editor):
    for game in Game.objects.all():
        logger.debug(f'calculating hfens for {game}')
        state = HexachromixState(variant=game.variant)
        for move in Move.objects.filter(game=game):
            state = state.make_move((move.q, move.r))
            logger.debug(f'{move} hfen is {state.hfen}')
            if not move.hfen:
                logger.debug(f'no hfen. setting {move} to {state.hfen}')
                move.hfen = state.hfen
                move.save(update_fields=['hfen'])
                logger.debug(f'saved {move}')
            else:
                logger.debug(f'{move} already has hfen {move.hfen}')


class Migration(migrations.Migration):
    dependencies = [
        ('hexachromix', '0013_alter_move_hfen'),
    ]

    operations = [
        migrations.RunPython(calc_hfen),
    ]
