name: Rebuild All Docker Images

on:
  push:
    branches:
      - master

jobs:
  #test:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4
      #- name: Set up Python
        #uses: actions/setup-python@v2
        #with:
          #python-version: '3.10'
      #- name: Install dependencies
        #run: pip install -r requirements.txt
      #- name: Run Tests
        #env:
          #USERNAME: ${{ secrets.TEST_USERNAME }}
          #PASSWORD: ${{ secrets.TEST_PASSWORD }}
        #run: python manage.py test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: taylorvance
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Nginx Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx/
          platforms: linux/arm64
          push: true
          tags: taylorvance/hexachromix:web-latest
      - name: Build Gunicorn Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/gunicorn/
          platforms: linux/arm64
          push: true
          tags: taylorvance/hexachromix:gunicorn-latest
      - name: Build Daphne Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/daphne/
          platforms: linux/arm64
          push: true
          tags: taylorvance/hexachromix:daphne-latest
